version: '3'

services:
  postgresql:
    image: postgres
    restart: always
    env_file: 
     - ./.env
    ports:
     - 5432:5432
    volumes:
     - ./data/postgresql:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
  api:
    build: ./api
    restart: always
    depends_on:
      - postgresql
    ports:
     - 8080:8080
    env_file:
     - ./.env
volumes:
  db_data: