name: Kalina
description: "Kalina"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_calendar: ^26.2.7
  table_calendar: ^3.1.2
  cupertino_icons: ^1.0.6
  uuid: ^4.4.2
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true